-- DEV-929: Media manager catalog, R2 config, and audit trail
--
-- Stores managed Cloudflare R2 media metadata for client websites.
-- Permanent R2 credentials remain server-only environment variables; this
-- schema stores only bucket/public URL/prefix configuration.

ALTER TABLE public.websites
    ADD CONSTRAINT websites_id_client_id_unique UNIQUE (id, client_id);

CREATE TABLE public.media_r2_configs (
    id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    client_id       uuid        REFERENCES public.clients(id) ON DELETE CASCADE,
    website_id      uuid        REFERENCES public.websites(id) ON DELETE CASCADE,
    bucket          text        NOT NULL,
    public_base_url text        NOT NULL,
    key_prefix      text        NOT NULL DEFAULT '',
    created_at      timestamptz NOT NULL DEFAULT timezone('utc', now()),
    updated_at      timestamptz NOT NULL DEFAULT timezone('utc', now()),
    CONSTRAINT media_r2_configs_scope_check CHECK (
        client_id IS NOT NULL OR website_id IS NOT NULL
    ),
    CONSTRAINT media_r2_configs_website_client_fk FOREIGN KEY (
        website_id,
        client_id
    ) REFERENCES public.websites (id, client_id) ON DELETE CASCADE,
    CONSTRAINT media_r2_configs_key_prefix_safe_check CHECK (
        key_prefix = ''
        OR (
            key_prefix = lower(key_prefix)
            AND key_prefix !~ '(^/|/$|//|\\.\\.)'
        )
    )
);

CREATE UNIQUE INDEX media_r2_configs_client_unique
    ON public.media_r2_configs (client_id)
    WHERE website_id IS NULL;

CREATE UNIQUE INDEX media_r2_configs_website_unique
    ON public.media_r2_configs (website_id)
    WHERE website_id IS NOT NULL;

CREATE INDEX media_r2_configs_client_id_idx
    ON public.media_r2_configs (client_id);

CREATE TABLE public.media_catalog_items (
    id                   bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    website_id           uuid        NOT NULL REFERENCES public.websites(id) ON DELETE CASCADE,
    client_id            uuid        NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
    key                  text        NOT NULL,
    filename             text        NOT NULL,
    src                  text        NOT NULL,
    alt                  text        NOT NULL DEFAULT '',
    service              text,
    sub_category         text,
    aspect_ratio         text,
    status               text        NOT NULL DEFAULT 'draft',
    sort_order           integer     NOT NULL DEFAULT 0,
    created_at           timestamptz NOT NULL DEFAULT timezone('utc', now()),
    updated_at           timestamptz NOT NULL DEFAULT timezone('utc', now()),
    archived_at          timestamptz,
    archived_by          text,
    archived_from_status text,
    CONSTRAINT media_catalog_items_key_unique UNIQUE (website_id, key),
    CONSTRAINT media_catalog_items_status_check CHECK (
        status IN ('draft', 'published', 'archived')
    ),
    CONSTRAINT media_catalog_items_archived_from_status_check CHECK (
        archived_from_status IS NULL
        OR archived_from_status IN ('draft', 'published')
    ),
    CONSTRAINT media_catalog_items_archived_state_check CHECK (
        status <> 'archived'
        OR (
            archived_at IS NOT NULL
            AND archived_from_status IS NOT NULL
        )
    ),
    CONSTRAINT media_catalog_items_website_client_fk FOREIGN KEY (
        website_id,
        client_id
    ) REFERENCES public.websites (id, client_id) ON DELETE CASCADE,
    CONSTRAINT media_catalog_items_aspect_ratio_check CHECK (
        aspect_ratio IS NULL
        OR aspect_ratio IN ('portrait', 'landscape', 'square', 'video')
    ),
    CONSTRAINT media_catalog_items_service_check CHECK (
        service IS NULL
        OR service IN ('Events', 'Family', 'Maternity', 'Couples', 'Portrait')
    ),
    CONSTRAINT media_catalog_items_sub_category_check CHECK (
        sub_category IS NULL
        OR sub_category IN (
            'Baby Shower',
            'Bridal Shower',
            'Gender Reveal',
            'Birthday',
            'Baptism',
            'Family',
            'Maternity',
            'Engagement',
            'Proposal',
            'Portrait'
        )
    ),
    CONSTRAINT media_catalog_items_service_sub_category_check CHECK (
        sub_category IS NULL
        OR (
            service = 'Events'
            AND sub_category IN (
                'Baby Shower',
                'Bridal Shower',
                'Gender Reveal',
                'Birthday',
                'Baptism'
            )
        )
        OR (service = 'Family' AND sub_category = 'Family')
        OR (service = 'Maternity' AND sub_category = 'Maternity')
        OR (
            service = 'Couples'
            AND sub_category IN ('Engagement', 'Proposal')
        )
        OR (service = 'Portrait' AND sub_category = 'Portrait')
    ),
    CONSTRAINT media_catalog_items_key_safe_check CHECK (
        key = lower(key)
        AND key !~ '(^/|/$|//|\\.\\.)'
    ),
    CONSTRAINT media_catalog_items_filename_safe_check CHECK (
        filename = lower(filename)
        AND filename !~ '(/|\\\\|\\.\\.)'
    )
);

CREATE INDEX media_catalog_items_website_status_idx
    ON public.media_catalog_items (website_id, status);

CREATE INDEX media_catalog_items_public_order_idx
    ON public.media_catalog_items (
        website_id,
        status,
        service,
        sub_category,
        sort_order
    );

CREATE INDEX media_catalog_items_archived_at_idx
    ON public.media_catalog_items (archived_at DESC)
    WHERE status = 'archived';

CREATE TABLE public.media_audit_logs (
    id          bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    website_id  uuid        NOT NULL REFERENCES public.websites(id) ON DELETE CASCADE,
    client_id   uuid        NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
    media_id    bigint      REFERENCES public.media_catalog_items(id) ON DELETE SET NULL,
    media_key   text,
    action      text        NOT NULL,
    actor       text,
    old_values  jsonb,
    new_values  jsonb,
    created_at  timestamptz NOT NULL DEFAULT timezone('utc', now()),
    CONSTRAINT media_audit_logs_action_check CHECK (
        action IN (
            'upload_created',
            'draft_saved',
            'published',
            'archived',
            'restored',
            'renamed_moved',
            'metadata_edited',
            'reorder_changed'
        )
    ),
    CONSTRAINT media_audit_logs_website_client_fk FOREIGN KEY (
        website_id,
        client_id
    ) REFERENCES public.websites (id, client_id) ON DELETE CASCADE
);

CREATE INDEX media_audit_logs_website_created_at_idx
    ON public.media_audit_logs (website_id, created_at DESC);

CREATE INDEX media_audit_logs_media_id_idx
    ON public.media_audit_logs (media_id);

CREATE INDEX media_audit_logs_action_idx
    ON public.media_audit_logs (action);

ALTER TABLE public.media_r2_configs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.media_catalog_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.media_audit_logs ENABLE ROW LEVEL SECURITY;

CREATE TRIGGER media_r2_configs_set_updated_at
BEFORE UPDATE ON public.media_r2_configs
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER media_catalog_items_set_updated_at
BEFORE UPDATE ON public.media_catalog_items
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
