-- DEV-950: Media placement assignments
--
-- Stores explicit frontend placement assignments for managed media.
-- Each placement row belongs to one website/client and points to one media item
-- owned by the same website/client. Clearing a placement deletes the row.

ALTER TABLE public.media_catalog_items
    ADD CONSTRAINT media_catalog_items_id_website_client_unique
    UNIQUE (id, website_id, client_id);

CREATE TABLE public.media_placements (
    id          bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    website_id  uuid        NOT NULL REFERENCES public.websites(id) ON DELETE CASCADE,
    client_id   uuid        NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
    slot_key    text        NOT NULL,
    media_id    bigint      NOT NULL,
    updated_by  text,
    created_at  timestamptz NOT NULL DEFAULT timezone('utc', now()),
    updated_at  timestamptz NOT NULL DEFAULT timezone('utc', now()),
    CONSTRAINT media_placements_slot_unique UNIQUE (website_id, slot_key),
    CONSTRAINT media_placements_slot_key_safe_check CHECK (
        slot_key = lower(slot_key)
        AND slot_key ~ '^[a-z0-9]+([._-][a-z0-9]+)*$'
    ),
    CONSTRAINT media_placements_website_client_fk FOREIGN KEY (
        website_id,
        client_id
    ) REFERENCES public.websites (id, client_id) ON DELETE CASCADE,
    CONSTRAINT media_placements_media_tenant_fk FOREIGN KEY (
        media_id,
        website_id,
        client_id
    ) REFERENCES public.media_catalog_items (
        id,
        website_id,
        client_id
    ) ON DELETE CASCADE
);

CREATE INDEX media_placements_website_slot_idx
    ON public.media_placements (website_id, slot_key);

CREATE INDEX media_placements_media_id_idx
    ON public.media_placements (media_id);

ALTER TABLE public.media_placements ENABLE ROW LEVEL SECURITY;

CREATE TRIGGER media_placements_set_updated_at
BEFORE UPDATE ON public.media_placements
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
